### ISSUE TITLE
Error reported at the end of the parsing step

### ISSUE THREAD

**Issue by verdurin** [WIMM-IT/slurm-analytics#4]
```
ERROR:2024-12-03 14:32:36,669: Dumps/cluster/sacct/sacct-output-2024-11-20_2024-11-27.csv, line 520946: Unable to convert field Timelimit to format td: 1-0: could not convert string to float: '1-0'
22248907_1890|<username>|2024-11-23T08:15:31|1-0
ERROR:2024-12-03 14:32:36,669: Dumps/cluster/sacct/sacct-output-2024-11-20_2024-11-27.csv, line 520946: Exception while processing fields, State (s): pop from empty list
22248907_1890|<username>|2024-11-23T08:15:31|1-0
Traceback (most recent call last):
  File "/gpfs3/well/rescomp/<username>/src/github/slurm-analytics/sacct-parse.py", line 88, in <module>
    d = slurmLogParser.parse_jobs_to_dict()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs3/well/rescomp/<username>/src/github/slurm-analytics/hpc-cost-simulator/SlurmLogParser.py", line 166, in parse_jobs_to_dict
    job = self.parse_job()
          ^^^^^^^^^^^^^^^^
  File "/gpfs3/well/rescomp/<username>/src/github/slurm-analytics/hpc-cost-simulator/SlurmLogParser.py", line 204, in parse_job
    parsed_line = self._parse_line(line)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs3/well/rescomp/<username>/src/github/slurm-analytics/hpc-cost-simulator/SlurmLogParser.py", line 308, in _parse_line
    if job_fields['AllocNodes'] == 0:
       ~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'AllocNodes'
```

**Comment by aowenson-imm** [comment]
I've pushed a fix to my branch of `hpc-cost-simulator`.

I've also redacted the usernames in the 2nd and 4th lines, not sure if you saw them.
